LABEL maintainer="Christoph Schranz <christoph.schranz@salzburgresearch.at>"

USER root

# Install nvtop to monitor the gpu tasks
RUN apt-get update && \
    apt-get install -y git nvtop && \
    rm -rf /var/lib/apt/lists/* && \
    fix-permissions /home/$NB_USER

USER $NB_UID
